services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  embedding-server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.0
    container_name: embedding-server
    ports:
      - "8088:80"
    environment:
      MODEL_ID: sentence-transformers/all-MiniLM-L6-v2
      MAX_INPUT_LENGTH: 512

  ollama:
    image: ollama/ollama
    container_name: ollama
    profiles: [ollama]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/entrypoint-ollama.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  discord-bot:
    build:
      context: .
      dockerfile: ./docker/discord-bot-Dockerfile
    container_name: discord-bot
    profiles: [discord-bot]
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_URI=mongodb://mongodb:27017
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_SERVER_URL=http://embedding-server:8088
      - OLLAMA_URL=http://ollama:11434

      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DEFAULT_AI_PROVIDER=${DEFAULT_AI_PROVIDER}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
    depends_on:
      - mongodb
      - qdrant
      - embedding-server
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

networks:
  shared-network:
    external: true
    
volumes:
  mongo_data:
  qdrant_storage:
  ollama_data:
